apiVersion: v1  #the version we are using
kind: Service  #it tells k8s that this is a service file    
metadata: 
  name: bankmysql   #this is the name of mysql services
spec:
  selector:
    app: bankmysql 
  ports: 
    - port: 3306   #this is the port on which it should run
  clusterIP: None # This means we are going to use Pod IP