apiVersion: v1            
kind: Service   #tells k8s that this is service
metadata:
  name: banking-service    #the name of the service class
  labels: 
    app: banking-app     #binds the appliation needs to be exposed to the network
spec:
  type: NodePort   #To specify where that  app needs to be run
  selector:
    app: banking-app
  ports: 
    - port: 80
      targetPort: 8080
      nodePort: 31231    #specified port number